version: '3'
services:
    prisma:
        image: prismagraphql/prisma:1.34
        restart: always
        ports:
            - '127.0.0.1:4466:4466'
        environment:
            PRISMA_CONFIG: |
                managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
                port: 4466
                databases:
                  default:
                    connector: mysql
                    host: mysql
                    port: 3306
                    user: root
                    password: prisma
                    migrations: true
    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - '127.0.0.1:3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: prisma
        volumes:
            - mysql:/var/lib/mysql
volumes:
    mysql: ~
