import Head from 'next/head';

const Meta = () => (
    <Head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto" />
        <meta charSet="utf-8" />
        <meta name="description" content="Rss/Atom feeds to email digester" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>FeedMailu - rss2email digests</title>
        {/* Icons generated by favicon-generator.org */}
        <link rel="apple-touch-icon" sizes="57x57" href="/static/_meta/apple-icon-57x57.png" />
        <link rel="apple-touch-icon" sizes="60x60" href="/static/_meta/apple-icon-60x60.png" />
        <link rel="apple-touch-icon" sizes="72x72" href="/static/_meta/apple-icon-72x72.png" />
        <link rel="apple-touch-icon" sizes="76x76" href="/static/_meta/apple-icon-76x76.png" />
        <link rel="apple-touch-icon" sizes="114x114" href="/static/_meta/apple-icon-114x114.png" />
        <link rel="apple-touch-icon" sizes="120x120" href="/static/_meta/apple-icon-120x120.png" />
        <link rel="apple-touch-icon" sizes="144x144" href="/static/_meta/apple-icon-144x144.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="/static/_meta/apple-icon-152x152.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/static/_meta/apple-icon-180x180.png" />
        <link rel="icon" type="image/png" sizes="192x192" href="/static/_meta/android-icon-192x192.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/static/_meta/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="96x96" href="/static/_meta/favicon-96x96.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/static/_meta/favicon-16x16.png" />
        <link rel="manifest" href="manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/static/_meta/ms-icon-144x144.png" />
        <meta name="theme-color" content="#ffffff" />
    </Head>
);

export default Meta;
